# Singular Value Decomposition

$A = U * \Sigma * V^T$

# Calculate Singular Value Decomposition

In [16]:
# Singular value decomposition
import numpy as np
from scipy.linalg import svd
# define a matrix
A = np.array([[1, 2],
              [3, 4],
              [5, 6]])
print(A)
U, S, VT = svd(A)
print(U)
print(S)
print(VT)

[[1 2]
 [3 4]
 [5 6]]
[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
[9.52551809 0.51430058]
[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


# Reconstruct Matrix from SVD

In [17]:
# Reconstruct SVD
import numpy as np

# create m x n zero Sigma matrix
Sigma = np.zeros(A.shape)

# populate Sigma with n x n diagonal matrix
k = min(A.shape)
print(k)
Sigma[:k, :k] = np.diag(S)
B = U.dot(Sigma.dot(VT))

2


In [18]:
print(B)

[[1. 2.]
 [3. 4.]
 [5. 6.]]


In [ ]:
def svd(lA):
    arrA = np.array(A)
    U, S, VT = svd(A)
    Sigma = np.zeros(A.shape)
    k = min(A.shape)
    Sigma[:k, :k] = np.diag(S)
    return U, Sigma, VT

# SVD for Pseudoinverse


The pseudoinverse is denoted as $A^+$, where $A$ is the matrix that is being inverted and + is a superscript.

$A^+ = VD^+U^T$

The $D^+$ can be calculated by creating a diagonal matrix from Sigma, calculating the reciprocal of each non-zero element in Sigma, and taking the transpose if the original matrix was rectangular.


In [20]:
# Pseudoinverse
# define matrix
A = np.array([[0.1, 0.2],
              [0.3, 0.4],
              [0.5, 0.6],
              [0.7,
               0.8]])
print(A)
# calculate pseudoinverse
B = np.linalg.pinv(A)
print(B)

[[0.1 0.2]
 [0.3 0.4]
 [0.5 0.6]
 [0.7 0.8]]
[[-1.0000000e+01 -5.0000000e+00  8.4040814e-15  5.0000000e+00]
 [ 8.5000000e+00  4.5000000e+00  5.0000000e-01 -3.5000000e+00]]


In [ ]:
def pinv(lA):
    arrA = np.array(A)
    U, s, VT = np.linalg.svd(A)
    d = 1.0/s
    D = np.zeros(A.shape)
    k = min(A.shape)
    D[:k, :k] = np.diag(d)
    return (VT.T).dot((D.T).dot(U.T))

In [ ]:
pinv(A)

In [ ]:
np.linalg.pinv(A)

# SVD for Dimensionality Reduction

In [19]:
def approximate(lA, n_components):
    arrA = np.array(lA)
    U, Sigma, VT = svd(arrA)
    Sigmak = Sigma[:, :n_components]
    VTk = VT[:n_components, :]
    print(U.shape, Sigmak.shape, VTk.shape)
    return U.dot(Sigmak.dot(VTk))

In [21]:
from sklearn.decomposition import TruncatedSVD
# define array
A = np.array([
	[1,2,3,4,5,6,7,8,9,10],
	[11,12,13,14,15,16,17,18,19,20],
	[21,22,23,24,25,26,27,28,29,30]])
print(A)
# svd
svd = TruncatedSVD(n_components=2)
svd.fit(A)
result = svd.transform(A)
print(result)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]
[[18.52157747  6.47697214]
 [49.81310011  1.91182038]
 [81.10462276 -2.65333138]]
