In [27]:
import numpy as np
from sympy import *


def get_m0(n: int):
    """
    get a fundamental matrix in statistics, "centering matrix" that is used to transform data to
    deviations from their mean
    :param n: length of data
    :return: $M_0$
    """
    return (-1 / n) * np.ones((n, n)) + np.eye(n)


def sum(array):
    n = array.shape[0]
    i = np.ones(n)

    return np.dot(i, array)

def mean(array):
    import numpy as np
    n = array.shape[0]
    i = np.ones(n)
    return (1 / n) * np.dot(i, array)


def mean_deviation(array):
    n = array.shape[0]
    m0 = get_m0(n)
    return np.matmul(m0, array)


def sum_of_squares(array):
    return np.sum(array ** 2)


def sum_of_squared_deviation(array):
    return sum_of_squares(mean_deviation(array))


def sum_of_squres_matrix(a, b):
    z = np.c_[a, b]
    return z.T.matmul(get_m0(z.shape[0])).matmul(z)


def rref(matrix):
    m = Matrix(matrix)
    return np.array(m.rref()[0].tolist()).astype(np.float64)

def rank(matrix):
    return np.linalg.matrix_ranK(matrix)

def det(matrix):
    return np.linalg.det(matrix)

def inv(matrix):
    return np.linalg.inv(matrix)

def l1_norm(matrix):
    return np.abs(np.array(matrix)).sum()

def l2_norm(matrix):
    return np.sqrt((np.array(matrix) ** 2).sum())

def dot(arr1, arr2):
    return np.dot(np.array(arr1), np.array(arr2))

def arccos(angle):
    return np.arccos(angle)

def arccos_deg(angle):
    return arccos(angle) * 180 / np.pi

def orthogonal(arr1, arr2):
    return dot(arr1, arr2) == 0

def normalize(v):
    return v/l2_norm(v)

def inner_product(x, y, A):
    x_arr = np.array(x)
    y_arr = np.array(y)
    A_arr = np.array(A)
    return np.matmul(np.matmul(x_arr, A_arr), y_arr.T)
def proj_matrix(U):
    U_arr = np.array(U)

    return U_arr.dot(inv(U_arr.T.dot(U_arr))).dot(U_arr.T)

def proj(v, U):
    v_arr = np.array(v)

    return proj_matrix(U).dot(v_arr)

def gram_schmidt(B):
    B_arr = np.array(B)
    for i in range(B_arr.shape[1]):
        if i == 0:
            U = normalize(B_arr[:, i])
            U = U.reshape(U.shape[0], -1)
        else:
            U_j = normalize(B_arr[:, i] - proj(B_arr[:, i], U))
            U = np.c_[U, U_j]
    return U

def rotate(x, deg):
    x_arr = np.array(x)
    rad = deg*np.pi/180
    return np.matmul(np.array([[np.cos(rad), -np.sin(rad)], [np.sin(rad), np.cos(rad)]]), x_arr)

class LinearRegression:

    def __init__(self):
        self._params_ = None
        self._intercept_ = None
        self._coef_ = None

    @property
    def params_(self):
        return self._params_

    @params_.setter
    def params_(self, params):
        import numpy as np
        self._params_ = np.array(params)

    @property
    def intercept_(self):
        return self._intercept_

    @intercept_.setter
    def intercept_(self, intercept):
        import numpy as np
        self._intercept_ = np.array(intercept)

    @property
    def coef_(self):
        return self._coef_

    @coef_.setter
    def coef_(self, coef):
        import numpy as np
        self._coef_ = np.array(coef)

    def fit(self, X, y):
        n = X.shape[0]
        ones = np.ones(n)
        feat = np.c_[X, ones]
        inv = np.linalg.inv(np.matmul(feat.T, feat))
        self.params_ = np.matmul(np.matmul(inv, feat.T), y)
        self.coef_ = self.params_[0]
        self.intercept_ = self.params_[1]
        print(self.params_)

    def predict(self, x):
        n = x.shape[0]
        feat = np.c_[x, np.ones(n)]
        return np.matmul(feat, self.params_)

# 1

$\langle x, y \rangle := x_1y_1 - (x_1y_2+x_2y_1)+2x_2y_2$

Positive definite and symmetric part is easy to prove.

$\langle ax+by, z \rangle = (ax_1+by_1)z_1 - ((ax_1+by_1)z_2+(ax_2+by_2)z_1)+2(ax_2+by_2)z_2 = a\langle x, z \rangle + b \langle y, z \rangle$ 

# 2

$\begin{bmatrix} 2 & 0 \\ 1 & 2 \end{bmatrix}$ is not symmetric.

# 3

## a

-3

## b

In [5]:
x = np.array([[1],
              [2],
              [3]])
y = np.array([[-1],
              [-1],
              [0]])
A = np.array([[2, 1, 0],
              [1, 3, -1],
              [0, -1, 2]])
np.matmul(np.matmul(x.T, A), y)

array([[-8]])

# 5

## a

In [6]:
U = np.array([[0, 1, -3, -3],
              [-1, -3, 4, -3],
              [2, 1, 1, 5],
              [0, -1, 2, 0],
              [2, 2, 1, 7]])
x = np.array([-1, -9, -1, 4, 1]).T
proj(x, U)

array([-1.        , -6.09090909, -0.27272727, -2.54545455,  1.72727273])

## b

In [7]:
l2_norm(x - proj(x, U))

7.236272269866313

# 6

## a

In [13]:
A =[[2, 1, 0],
    [1, 2, -1],
    [0, -1, 2]]
e_1 = [1, 0, 0]
e_2 = [0, 1, 0]
e_3 = [0, 0, 1]

In [19]:
proj12 = inner_product(e_1, e_2, A) / inner_product(e_1, e_1, A) * np.array(e_1)
proj32 = inner_product(e_3, e_2, A) / inner_product(e_3, e_3, A) * np.array(e_3)
proj12+proj32

array([ 0.5,  0. , -0.5])

## b

In [21]:
np.sqrt(inner_product(np.array(e_2) - proj12+proj32, np.array(e_2) - proj12+proj32, A))

1.7320508075688772

# 7

$ (\mbox{id}_V - \pi) \circ (\mbox{id}_V - \pi) = (\mbox{id}_V - \pi)$

# 3.8

In [24]:
gram_schmidt([[1, -1],
              [1, 2],
              [1, 0]])

array([[ 0.57735027, -0.6172134 ],
       [ 0.57735027,  0.77151675],
       [ 0.57735027, -0.15430335]])

# 9

## a


$x = (x_1, \dots, x_n), y = (1, \dots, 1)$

$ (\Sigma_{i=1}^n x_iy_i)^2 \leq (\Sigma_{i=1}^n x_i^2)(\Sigma_{i=1}^n y_i^2)$

## b

$ x = (\sqrt{x_1}, \dots, \sqrt{x_n})$

$ y = (\sqrt{\frac{1}{x_1}}, \dots, \sqrt{\frac{1}{x_n}})$

# 10

In [28]:
x_1 = [2, 3]
rotate(x_1, 30)

array([0.23205081, 3.59807621])

In [29]:
x_2 = [0, -1]
rotate(x_1, 30)

array([0.23205081, 3.59807621])