# 2.1

## a
1. commutative: $a*b=ab+a+b=ba+b+a=b*a$.

2. associative: $a*(b*c)=a(b*c)+a+b*c=a(bc+b+c)+a+bc+b+c=abc+ab+ac+a+bc+b+c=abc+ac+bc+ab+a+b+c=(a*b)*c$

3. the existence of identity: $a*0=a$

4. the existence of inverse element for each element: $a*b=ab+a+b=0$, $b(a+1)=-a$, $b= \frac{-a}{a+1}$. The division holds $a\in \mathbb{R} - \{-1\}$

## b

$ 3*x*x=(3x+3+x)*x=3x^2+3x+x^2+3x+3+x+x=4x^2+8x+3=15, x^2+2x-3=0, (x+3)(x-1) = 0 $`



  

# 2.2

## a

1. commutative: $\bar{a} \oplus (\bar{b} \oplus \bar{c}) = \bar{a} \oplus \overline{b+c}= \overline{a+(b+c)}=\overline{(a+b)+c}=\overline{a+b}+\bar{c}=(\bar{a}\oplus\bar{b})\oplus\bar{c}$

2. the existence of idenetity: $\bar{a} \oplus \bar{0} = \overline{a+0}=\overline{a}$

3. the exsistence of inverse element for each element: $\overline{a} \oplus \overline{-a} = \bar{0}$

4. Abelian. Trivial.

## b

| $\mathbb{z} - \bar{0}$ | $\bar{1}$  | $\bar{2}$  | $\bar{3}$   | $\bar{4}$   |
| --- | --- | --- | --- | --- |
| $\bar{1}$ | $\bar{1}$ | $\bar{2}$ | $\bar{3}$ | $\bar{4}$ |
| $\bar{2}$ | $\bar{2}$ | $\bar{4}$ | $\bar{1}$ | $\bar{3}$ |
| $\bar{3}$ | $\bar{3}$ | $\bar{1}$ | $\bar{4}$ | $\bar{2}$ |
| $\bar{4}$ | $\bar{4}$ | $\bar{3}$ | $\bar{2}$ | $\bar{1}$ |

Considering the table above $(\mathbb{z}-\bar{0}, \otimes )$ is a Abelian group.

## C

$\bar{2}\otimes\bar{4}=\bar{0}$

## d(Bézout's Identity)

Just a brief outline. 
1. If ($\mathbb{z}_n - \bar{0}, \otimes)$ is a group, then $n \in \mathbb{N} - {0}$ is a prime.

For any $a\in \mathbb{z}_n - \bar{0}$, there exists $u \in \mathbb{z}_n - \bar{0} $ such that $au = \bar{1}$.

2. If $n \in \mathbb{N} - {0}$ is a prime, then ($\mathbb{z}_n - \bar{0}, \otimes)$ is a group.

Since $n$ is a prime for any integer a, there exist $u$ and $v$ such that $au+nv=1$. Divide modulo $n$.

# 2.3

## closed under operation
$\begin{bmatrix}
1 & x & y \\
0 & 1 & z \\
0 & 0 & 1 \\
\end{bmatrix} \begin{bmatrix}
1 & a & b \\
0 & 1 & c \\
0 & 0 & 1 \\
\end{bmatrix} = \begin{bmatrix}
1 & x+a & y + b + cx \\
0 & 1 & z + c \\
0 & 0 & 1 \\
\end{bmatrix}$

## the existence of inverse element for each member
$a = -x \\
c = -z  \\
b = -y+zx $



# 2.4

In [ ]:
import numpy as np
from sympy import *


def get_m0(n: int):
    """
    get a fundamental matrix in statistics, "centering matrix" that is used to transform data to
    deviations from their mean
    :param n: length of data
    :return: $M_0$
    """
    return (-1 / n) * np.ones((n, n)) + np.eye(n)


def sum(array):
    n = array.shape[0]
    i = np.ones(n)

    return np.dot(i, array)

def mean(array):
    import numpy as np
    n = array.shape[0]
    i = np.ones(n)
    return (1 / n) * np.dot(i, array)


def mean_deviation(array):
    n = array.shape[0]
    m0 = get_m0(n)
    return np.matmul(m0, array)


def sum_of_squares(array):
    return np.sum(array ** 2)


def sum_of_squared_deviation(array):
    return sum_of_squares(mean_deviation(array))


def sum_of_squres_matrix(a, b):
    z = np.c_[a, b]
    return z.T.matmul(get_m0(z.shape[0])).matmul(z)


def rref(matrix):
    m = Matrix(matrix)
    return np.array(m.rref()[0].tolist()).astype(np.float64)

def rank(matrix):
    return np.linalg.matrix_ranK(matrix)


class LinearRegression:

    def __init__(self):
        self._params_ = None
        self._intercept_ = None
        self._coef_ = None

    @property
    def params_(self):
        return self._params_

    @params_.setter
    def params_(self, params):
        import numpy as np
        self._params_ = np.array(params)

    @property
    def intercept_(self):
        return self._intercept_

    @intercept_.setter
    def intercept_(self, intercept):
        import numpy as np
        self._intercept_ = np.array(intercept)

    @property
    def coef_(self):
        return self._coef_

    @coef_.setter
    def coef_(self, coef):
        import numpy as np
        self._coef_ = np.array(coef)

    def fit(self, X, y):
        n = X.shape[0]
        ones = np.ones(n)
        feat = np.c_[X, ones]
        inv = np.linalg.inv(np.matmul(feat.T, feat))
        self.params_ = np.matmul(np.matmul(inv, feat.T), y)
        self.coef_ = self.params_[0]
        self.intercept_ = self.params_[1]
        print(self.params_)

    def predict(self, x):
        n = x.shape[0]
        feat = np.c_[x, np.ones(n)]
        return np.matmul(feat, self.params_)

# a.

## b

In [ ]:
np.array([[1, 2, 3], [4, 5, 6], [7, 8 ,9]]) @ np.array([[1, 1, 0], [0, 1, 1], [1, 0, 1]])

array([[ 4,  3,  5],
       [10,  9, 11],
       [16, 15, 17]])

## c

In [ ]:
np.array([[1, 1, 0], [0, 1, 1], [1, 0, 1]]) @ np.array([[1, 2, 3], [4, 5, 6], [7, 8 ,9]])

array([[ 5,  7,  9],
       [11, 13, 15],
       [ 8, 10, 12]])

## d

In [ ]:
np.array([[1, 2, 1, 2], [4, 1, -1, -4]]) @ np.array([[0, 3], [1, -1], [2, 1], [5, 2]])

array([[ 14,   6],
       [-21,   2]])

## e

# 2.5

## a
no solutions

In [ ]:
rref([[1, 1, -1, -1, 1], [2, 5, -7, -5, -2], [2, -1, 1, 3, 4], [5, 2, -4, 2, 6]])

array([[ 1.        ,  0.        ,  0.        ,  0.66666667,  0.        ],
       [ 0.        ,  1.        ,  0.        , -2.66666667,  0.        ],
       [ 0.        ,  0.        ,  1.        , -1.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  1.        ]])

## b

In [ ]:
rref([[1, -1, 0, 0, 1, 3], [1, 1, 0, -3, 0, 6], [2, -1, 0, 1, -1, 5], [-1, 2, 0, -2, -1, -1]])

array([[ 1.,  0.,  0.,  0., -1.,  3.],
       [ 0.,  1.,  0.,  0., -2.,  0.],
       [ 0.,  0.,  0.,  1., -1., -1.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

$\{
\begin{bmatrix}
3 \\
0 \\
0 \\
-1 \\
0 \\
\end{bmatrix}
+
\begin{bmatrix}
-1 \\
-1 \\
-1 \\
-1 \\
-1 \\
\end{bmatrix}x_3
+\begin{bmatrix}
-1 \\
-2 \\
-1 \\
0 \\
-1 \\
\end{bmatrix}x_5 : x_1, x_5 \in \mathbb{F}
\}$

# 6

$\{
\begin{bmatrix}
-1 \\
-1 \\
-1 \\
-1 \\
-1 \\
-1 \\
\end{bmatrix}x_1
+
\begin{bmatrix}
0 \\
-1 \\
0 \\
-1 \\
1 \\
1 \\
\end{bmatrix}x_2
+\begin{bmatrix}
-1 \\
-1 \\
-1 \\
-1 \\
-1 \\
-1 \\
\end{bmatrix}x_3
+\begin{bmatrix}
 \\
 \\
 \\
-3 \\
 \\
 \\
\end{bmatrix}
+\begin{bmatrix}
 \\
 \\
 \\
 \\
2 \\
 \\
\end{bmatrix}
+\begin{bmatrix}
 \\
 \\
 \\
 \\
 \\
1 \\
\end{bmatrix} : x_1, x_2, x_3 \in \mathbb{F}
\}$

# 2.7

In [ ]:
rref([[-6, 4, 3], [6, -12, 9], [0, 8, -12]])

array([[ 1. ,  0. , -1.5],
       [ 0. ,  1. , -1.5],
       [ 0. ,  0. ,  0. ]])

$\begin{bmatrix}
-1.5 \\
-1.5 \\
-1 \\
\end{bmatrix}x_3$, with $-4x_3 = 1$, which implies

$\begin{bmatrix}
3/8 \\
3/8 \\
4/1 \\
\end{bmatrix}$

# 2.8

In [ ]:
def det(matrix):
    return np.linalg.det(matrix)

## a

In [ ]:
det([[2, 3, 4], [3, 4, 5], [4, 5, 6]])

0.0

## b

In [ ]:
det([[1, 0, 1, 0,], [0, 1, 1, 0], [1, 1, 0, 1], [1, 1, 1, 0]])

1.0

In [ ]:
def inv(matrix):
    return np.linalg.inv(matrix)

In [ ]:
inv([[1, 0, 1, 0,], [0, 1, 1, 0], [1, 1, 0, 1], [1, 1, 1, 0]])

array([[ 0., -1.,  0.,  1.],
       [-1.,  0.,  0.,  1.],
       [ 1.,  1., -0., -1.],
       [ 1.,  1.,  1., -2.]])

# 2.9

b

# 2.10

## a

In [ ]:
rref([[2, 1, 3,], [-1, 1, -3], [3, -2, 8]])

array([[ 1.,  0.,  2.],
       [ 0.,  1., -1.],
       [ 0.,  0.,  0.]])

## b

In [ ]:
rref([[1, 1, 1], [2, 1, 0], [1, 0, 0], [0, 1, 1], [0, 1, 1]])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

Linearly independent.

# 2.11

In [ ]:
rref([[1, 1, 2, 1], [1, 2, -1, -2], [1, 3, 1, 5]])

array([[ 1.,  0.,  0., -6.],
       [ 0.,  1.,  0.,  3.],
       [ 0.,  0.,  1.,  2.]])

# 2.12

In [ ]:
rref([[1, 2, -1, -1, 2, -3], [1, -1, 1, -2, -2, 6], [-3, 0, -1, 2, 0, -2], [1, -1, 1, 1, 0, -1]])

array([[ 1.        ,  0.        ,  0.33333333,  0.        ,  0.44444444,
        -0.88888889],
       [ 0.        ,  1.        , -0.66666667,  0.        ,  1.11111111,
        -2.22222222],
       [ 0.        ,  0.        ,  0.        ,  1.        ,  0.66666667,
        -2.33333333],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ]])

$\begin{bmatrix}
1 \\
1 \\
-3 \\
1 \\
\end{bmatrix},
\begin{bmatrix}
2 \\
1- \\
0 \\
-1 \\
\end{bmatrix},
\begin{bmatrix},
1 \\
-2 \\
2 \\
1 \\
\end{bmatrix}$

# 2.13

In [ ]:
A1 = np.array([[1, 0, 1],
                [1, -2, -1],
                [2, 1, 3],
                [1, 0 ,1]])
A2 = np.array([[3, -3, 0],
               [1, 2, 3],
               [7, -5, 2], 
               [3, -1, 2]])

In [ ]:
rref(A1)

array([[1., 0., 1.],
       [0., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
rref(A2)

array([[1., 0., 1.],
       [0., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

$U_1 = U_2 = \mbox{span}(\begin{bmatrix} 1 \\ 1 \\ -1 \\ 0 \end{bmatrix})$


# 2.15

## a.

## b
$ x+y-z = 0 \\ x + y - z = a+3b = 0 \\ a = -3b$
$ (x, y, z) = (-4b, -2b, -6b) = (2, 1, 3)b$

## c

$F = \mbox{span}(\begin{bmatrix} 1 \\ -1 \\ 0\end{bmatrix}, \begin{bmatrix} -1 \\ 0 \\ -1\end{bmatrix})$

$G = \mbox{span}(\begin{bmatrix} 1 \\ 1 \\ 1\end{bmatrix}, \begin{bmatrix} -1 \\ 1 \\ -3\end{bmatrix})$

In [ ]:
rref([[1, -1, -1, 1], [-1, 0, -1, -1], [0, -1, -1, 3]])

array([[ 1.,  0.,  0., -2.],
       [ 0.,  1.,  0., -6.],
       [ 0.,  0.,  1.,  3.]])

$\begin{bmatrix} 3 \\ 3 \\ 3\end{bmatrix} + \begin{bmatrix} 1 \\ -1 \\ 3\end{bmatrix} = \begin{bmatrix} 4 \\ 2 \\ 6 \end{bmatrix}$

# 2.16

They are all linear mappings except for c.

## 2.18

# 2.19

## a

In [ ]:
rref([[1, 1, 0], [1, -1, 0], [1, 1, 1]])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

$\mbox{ker}{\Phi} = {0}, \mbox{Im}\Phi = \mathbb{R}^3$



## b

In [ ]:
tf = np.array([[1, 1, 1], [1, 2, 0], [1, 1, 0]])

In [ ]:
inv(tf) @ np.array([[1, 1, 0], [1, -1, 0], [1, 1, 1]]) @ tf

array([[ 6.,  9.,  1.],
       [-3., -5.,  0.],
       [-1., -1.,  0.]])

$\begin{bmatrix} 2 & -1 \\ 1 & -1 \end{bmatrix}\begin{bmatrix} x \\ y \end{bmatrix} = \begin{bmatrix} 2 & 1 \\ -2 & 1 \end{bmatrix}\begin{bmatrix} a \\ b \end{bmatrix}$

In [ ]:
inv([[2, -1], [1, -1]]) @ np.array([[2, 1], [-2, 1]])

array([[ 4.,  0.],
       [ 6., -1.]])

## c

In [ ]:
det([[1, 0 , 1], [2, -1, 0], [-1, 2, -1]])

3.999999999999999

In [ ]:
P2 = np.array([[1, 0 , 1], [2, -1, 0], [-1, 2, -1]])

$\Phi(b_1)= c_1 +2c_3$

$\Phi(b_2)= -c_1 +c_2-c_3$

$A_\Phi = \begin{bmatrix} 1 & -1 \\ 0 & 1\\ 2 & -1 \end{bmatrix}$



## e

In [ ]:
P2 @ np.array([[1, -1], [0, 1], [2, -1]]) @ np.array([[4, 0], [6, -1]])

array([[  0,   2],
       [-10,   3],
       [ 12,  -4]])

In [ ]:
np.array([[4, 0], [6, -1]]) @ np.array([[2], [3]])

array([[8],
       [9]])

In [ ]:
np.array([[1, -1], [0, 1], [2, -1]]) @ _

array([[-1],
       [ 9],
       [ 7]])

In [ ]:
P2 @ _

array([[  6],
       [-11],
       [ 12]])

In [ ]:
P2 @ np.array([[1, -1], [0, 1], [2, -1]]) @ np.array([[4, 0], [6, -1]]) @ np.array([[2], [3]])

array([[  6],
       [-11],
       [ 12]])